<?php
namespace app\admin\controller;

use app\common\logic\OrderLogic;


class Order extends Base
{

    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //订单列表
    public function index(){
        $logic = new OrderLogic();
        $order = $logic->get_all_order();
//        $page = $order->render();//分页页码

//        $this->assign('page',$page);
        $this->assign('order',$order);
        return $this->fetch();
    }

    //订单详情
    public function detail(){
        $orderid=input('orderid');

        $logic = new OrderLogic();
        $where = ['a.id'=>$orderid];
        $order = $logic->get_one_order($where);
//    dump($order);
        $this->assign('order',$order);
        return $this->fetch();
    }


}
